image: atlassian/default-image:3

pipelines:
  branches:
    release/staging:
      - step:
          name: Deploy to dev.37rally.com
          deployment: staging
          script:
            - ssh $USER_NAME@$HOST_NAME "cd $PUBLIC_PATH && sh deploy.sh"
    release/test:
      - step:
          name: Deploy to test.37rally.com
          deployment: test
          script:
            - ssh $USER_NAME@$HOST_NAME "cd $PUBLIC_PATH && sh deploy.sh"
    release/beta:
      - step:
          name: Deploy to beta.37rally.com
          deployment: beta
          script:
            - ssh $USER_NAME@$HOST_NAME "cd $PUBLIC_PATH && sh deploy.sh"