const BUSINESS_PATH = '/business';

export const PATHS = {
  dashboard: '/',
  login: '/login',
  businessManagement: '/business-management',
  businessDetail: '/business-detail',
  userManagement: '/user-management',
  seriesDetail: '/series-detail',
  businessNew: '/business-new',
  eventDetail: '/event-detail',
  userNew: '/user-new',
  userDetail: '/user-detail',
  seriesNew: '/series-new',
  masterApplicationList: '/master-application-list',
  masterApplicationDetail: '/master-application-detail',
  bannerAdministration: '/banner-administration',
  bannerDetail: '/banner-detail',
  bannerNew: '/banner-new',
  eventRegistration: '/event-registration',
  eventRegistrationSpot: '/event-registration-spot',
  eventRegistrationSpotSetting: '/event-registration-spot-setting',
  eventRegistrationSystemSetting: '/event-registration-system-setting',
  recommendationManagement: '/recommendation-management',
  notificationManagement: '/notification-management',
  notificationRegistration: '/notification-registration',
  notificationDetail: '/notification-detail',
  featuredManagement: '/featured-management',
  rallyMyPageSpotDetail: '/rally/mypage/spot-detail-checkin',
  business: {
    dashboard: `/`,
    home: `${BUSINESS_PATH}`,
    login: `${BUSINESS_PATH}/login`,
    forgotPassword: `${BUSINESS_PATH}/forgot-password`,
    resetPassword: `${BUSINESS_PATH}/reset-password`,
    info: `${BUSINESS_PATH}/info`,
    grandRallyManagement: `${BUSINESS_PATH}/grand-rally-management`,
    newGranRally: `${BUSINESS_PATH}/new-grand-rally`,
    rallyManagement: `${BUSINESS_PATH}/rally-management`,
    playerManagement: `${BUSINESS_PATH}/player-management`,
    playerDetail: `${BUSINESS_PATH}/player-detail`,
    newRally: `${BUSINESS_PATH}/new-rally`,
    grandRallyDetail: `${BUSINESS_PATH}/grand-rally`,
    rallyDetail: `${BUSINESS_PATH}/rally`,
    newRallySpotList: `${BUSINESS_PATH}/new-rally-spots`,
    editSpot: `${BUSINESS_PATH}/edit-spot`,
    newRallySystemSetting: `${BUSINESS_PATH}/new-rally-system-setting`,
    rewardManagement: `${BUSINESS_PATH}/reward-management`,
    rewardManagementDetail: `${BUSINESS_PATH}/reward-detail`
  }
};
